<?php

/**
 * @file
 * Contains CER's implementation of the Hierarchical Select API.
 */

/**
 * Implements hook_hierarchical_select_params().
 */
function cer_hs_hierarchical_select_params() {
  return array('id');
}

/**
 * Implements hook_hierarchical_select_root_level().
 */
function cer_hs_hierarchical_select_root_level($parameters) {
  return CerHierarchyHS::get($parameters['id'])->getOptions(CerHierarchy::ROOT);
}

/**
 * Implements hook_hierarchical_select_children().
 */
function cer_hs_hierarchical_select_children($parent, $parameters) {
  return CerHierarchyHS::get($parameters['id'])->getOptions($parent);
}

/**
 * Implements hook_hierarchical_select_lineage().
 */
function cer_hs_hierarchical_select_lineage($item, $parameters) {
  return CerHierarchyHS::get($parameters['id'])->getLineage($item);
}

/**
 * Implements hook_hierarchical_select_valid_item().
 */
function cer_hs_hierarchical_select_valid_item($item, $parameters) {
  return CerHierarchyHS::get($parameters['id'])->validItem($item);
}

/**
 * Implements hook_hierarchical_select_item_get_label().
 */
function cer_hs_hierarchical_select_item_get_label($item, $parameters) {
  return CerHierarchyHS::get($parameters['id'])->getLabel($item);
}
