<?php

/**
 * Implements hook_entity_property_info_alter().
 */
function cer_profile2_entity_property_info_alter(array &$info) {
  $struct = &$info['profile2']['properties']['cer']['property info'];

  $struct['lineage']['getter callback'] = 'cer_profile2_get_profile2_lineage';
  $struct['depth']['getter callback'] = 'cer_profile2_get_profile2_depth';
  $struct['owner']['getter callback'] = 'cer_profile2_get_profile2_owner';
}

function cer_profile2_get_profile2_lineage(array $data, array $options, $property, $data_type, array $info) {
  return 'user:user:profile_' . $data[1]->type . ':profile2:' . $data[1]->type . ':';
}

function cer_profile2_get_profile2_depth(array $data, array $options, $property, $data_type, array $info) {
  return 1;
}

function cer_profile2_get_profile2_owner(array $data, array $options, $property, $data_type, array $info) {
  return new EntityDrupalWrapper('user', $data[1]->user());
}
