<?php

/**
 * Implements hook_query_TAG_alter().
 */
function cer_entity_settings_query_cer_presets_alter(QueryAlterableInterface $query) {
  $entity = $query->getMetaData('entity');

  $instance = field_info_instance($entity->type(), 'cer_settings', $entity->getBundle());
  if ($instance) {
    $IDs = array();
    foreach ($entity->cer_settings as $preset) {
      $IDs[] = $preset->getIdentifier();
    }

    if ($IDs) {
      $query->getMetaData('entity_field_query')->entityCondition('entity_id', $IDs, 'IN');
    }

    if (! $entity->cer_store_settings->value()) {
      $queue = &drupal_static('cer_entity_settings_exit', array());
      $queue[ $entity->type() ][ $entity->getIdentifier() ] = $entity;
    }
  }
}

/**
 * Implements hook_exit().
 */
function cer_entity_settings_exit() {
  $queue = drupal_static(__FUNCTION__, array());

  foreach ($queue as $entity_type => $entities) {
    foreach ($entities as $entity) {
      $entity->cer_settings->set(NULL);

      $entity = $entity->value();
      field_attach_presave($entity_type, $entity);
      field_attach_update($entity_type, $entity);
    }
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 */
function cer_entity_settings_ctools_plugin_directory($owner, $plugin_type) {
  return "plugins/{$owner}/{$plugin_type}";
}

/**
 * Implements hook_cer_insert().
 */
function cer_entity_settings_cer_insert(CerPreset $preset) {
  _cer_entity_settings_create_instance($preset->wrapper->cer_left->chain->value());
  _cer_entity_settings_create_instance($preset->wrapper->cer_right->chain->value());
}

/**
 * Implements hook_cer_update().
 */
function cer_entity_settings_cer_update(CerPreset $preset) {
  cer_entity_settings_cer_insert($preset);
}

function _cer_entity_settings_create_instance(FieldChain $chain) {
  $field = $chain->end();

  $instance = field_info_instance($field->entityType, 'cer_settings', $field->bundle);
  if (! $instance) {
    $instance = array(
      'bundle' => $field->bundle,
      'default_value' => NULL,
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'entityreference',
          'settings' => array(
            'link' => FALSE,
          ),
          'type' => 'entityreference_label',
          'weight' => 1,
        ),
      ),
      'entity_type' => $field->entityType,
      'field_name' => 'cer_settings',
      'label' => t('Synchronize this @entity_type with...', array(
        '@entity_type' => $field->entityTypeLabel,
      )),
      'required' => 0,
      'settings' => array(
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(
          'match_operator' => 'CONTAINS',
          'path' => '',
          'size' => 60,
        ),
        'type' => 'options_buttons',
        'weight' => 1,
      ),
    );
    field_create_instance($instance);
    
    $instance = array(
      'bundle' => $field->bundle,
      'default_value' => array(
        0 => array(
          'value' => 1,
        ),
      ),
      'deleted' => 0,
      'description' => '',
      'display' => array(
        'default' => array(
          'label' => 'above',
          'module' => 'list',
          'settings' => array(),
          'type' => 'list_default',
          'weight' => 2,
        ),
        'teaser' => array(
          'label' => 'above',
          'settings' => array(),
          'type' => 'hidden',
          'weight' => 0,
        ),
      ),
      'entity_type' => $field->entityType,
      'field_name' => 'cer_store_settings',
      'label' => t('Remember these settings'),
      'required' => 0,
      'settings' => array(
      ),
      'widget' => array(
        'active' => 1,
        'module' => 'options',
        'settings' => array(
          'display_label' => 1,
        ),
        'type' => 'options_onoff',
        'weight' => 2,
      ),
    );
    field_create_instance($instance);
  }
}
